"""adding catagories & products assoc

Revision ID: 13f3f8a07be6
Revises: e658261b9efe
Create Date: 2022-12-16 14:25:22.584007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f3f8a07be6'
down_revision = 'e658261b9efe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
