"""adding qty table and its relational entity

Revision ID: 2e0bf557e78b
Revises: d1ca2133fe8a
Create Date: 2022-12-18 22:12:55.140698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = "2e0bf557e78b"
down_revision = "d1ca2133fe8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_order_quantities",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(
                always=False, start=1, maxvalue=999999999999999999999999999, cycle=True
            ),
            nullable=False,
        ),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.alter_column("orderes", "created_at", existing_type=oracle.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column("orderes", "created_at", existing_type=oracle.DATE(), nullable=True)
    op.drop_table("product_order_quantities")
    # ### end Alembic commands ###
