"""adding column in address table

Revision ID: 49b66e2d988e
Revises: ca511454e492
Create Date: 2022-12-15 23:14:16.190817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b66e2d988e'
down_revision = 'ca511454e492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('present_address', sa.String(length=255), nullable=False))
    op.add_column('addresses', sa.Column('permenent_address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'permenent_address')
    op.drop_column('addresses', 'present_address')
    # ### end Alembic commands ###
