"""changed optional params

Revision ID: 654f2756cbc7
Revises: ad8e3a925324
Create Date: 2022-12-17 21:29:51.616117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654f2756cbc7'
down_revision = 'ad8e3a925324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
