"""adding order table with many to many relationship with products

Revision ID: ad8e3a925324
Revises: 13f3f8a07be6
Create Date: 2022-12-16 14:44:03.571786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8e3a925324'
down_revision = '13f3f8a07be6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, maxvalue=999999999999999999999999999, cycle=True), nullable=False),
    sa.Column('invoice_no', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_order_assoc',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, maxvalue=999999999999999999999999999, cycle=True), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orderes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_order_assoc')
    op.drop_table('orderes')
    # ### end Alembic commands ###
