"""adding customer & address table

Revision ID: ca511454e492
Revises: 
Create Date: 2022-12-15 23:11:41.816756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca511454e492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, maxvalue=999999999999999999999999999, cycle=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, maxvalue=999999999999999999999999999, cycle=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    op.drop_table('customers')
    # ### end Alembic commands ###
