"""column length changed in customer contactnumber

Revision ID: d10d9d4de27b
Revises: 49b66e2d988e
Create Date: 2022-12-15 23:39:55.773500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10d9d4de27b'
down_revision = '49b66e2d988e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
