"""adding column in Order table

Revision ID: d1ca2133fe8a
Revises: 654f2756cbc7
Create Date: 2022-12-18 21:31:33.554663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1ca2133fe8a"
down_revision = "654f2756cbc7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orderes", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orderes", "created_at")
    # ### end Alembic commands ###
