"""adding primary_key in product_tag_assoc tbl

Revision ID: e658261b9efe
Revises: bf04baa0c38d
Create Date: 2022-12-16 13:54:19.412073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e658261b9efe"
down_revision = "bf04baa0c38d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_tag_assoc",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(
                always=False, start=1, maxvalue=999999999999999999999999999, cycle=True
            ),
            nullable=False,
            primary_key=True,
        ),
    )
    op.alter_column(
        "products",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(always=False, start=1, nomaxvalue=False),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tags",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(always=False, start=1, nomaxvalue=False),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tags",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            on_null=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=9999999999999999999999999999,
            cycle=False,
            cache=20,
            order=False,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "products",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            on_null=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=9999999999999999999999999999,
            cycle=False,
            cache=20,
            order=False,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("product_tag_assoc", "id")
    # ### end Alembic commands ###
